# Generated by Django 4.0.6 on 2022-10-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_unitprice_goods_cangku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='createtime',
        ),
    ]
