# Generated by Django 4.0.6 on 2022-10-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_goods_createtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20, null=True)),
                ('customer_phone', models.CharField(max_length=20, null=True)),
                ('customer_sex', models.CharField(max_length=20, null=True)),
                ('customer_jifen', models.CharField(max_length=20, null=True)),
                ('customer_total_buy', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, null=True)),
                ('customer_phone', models.CharField(max_length=20, null=True)),
                ('goods_chima', models.CharField(max_length=20, null=True)),
                ('goods_huohao', models.CharField(max_length=20, null=True)),
                ('goods_name', models.CharField(max_length=20, null=True)),
                ('sell_price', models.CharField(max_length=20, null=True)),
                ('goods_type', models.CharField(max_length=20, null=True)),
                ('goods_pici', models.CharField(max_length=20, null=True)),
                ('goods_tiaoma', models.CharField(max_length=20, null=True)),
                ('goods_cangku', models.CharField(max_length=20, null=True)),
                ('goods_shuliang', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
