# Generated by Django 4.0.6 on 2022-10-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
